### ISSUE TITLE
Unable to install pytorch bindings with cuda 11.3

### ISSUE THREAD

**Issue by akshay-krishnan** [NVlabs/tiny-cuda-nn#183]
I am trying to build the pytorch bindings, but I am unable to because lcuda was not found on my system. 
`ld: cannot find -lcuda ` 
I have cuda installed in `/usr/local/cuda-11.3` and added `/usr/local/cuda-11.3/bin` to my `$PATH` and `/usr/local/cuda-11.3/lib64/` to my `$LD_LIBRARY_PATH`. 

I am able to build the library itself with cmake, but no success with the torch bindings. 
The g++ command fails since it is unable to find lcuda. I also cannot find a libcuda.so in my `/usr/local/cuda-11.3/lib64/`. I found one in `/usr/local/cuda-11.3/lib64/stubs/`, and added this path to my LD_LIBRARY_PATH, but that did not help. 

I appreciate any help on this.

**Comment by bdfbdf321** [comment]
> 

have you solved this problem？

**Comment by akshay-krishnan** [comment]
Yes, it could have been specific to my environment setup (or to my cuda version 11.3). I had to manually link to the `libcuda.so` in my conda environment lib.

**Comment by bdfbdf321** [comment]
@akshay-krishnan How to link libcuda.so ? could you say more details about this solution. I still have this problem.

**Comment by ry85** [comment]
@akshay-krishnan How did you manually linked libcuda.so?

**Comment by akshay-krishnan** [comment]
Sorry for the late response folks. 

There was a libcuda.so in this path on my system `/lib/x86_64-linux-gnu/libcuda.so`, but I think that path is not included in LD's library path. 
I saw that the linked library path in my command is the /lib folder in my conda environment (`miniconda3/envs/<env_name>/lib/libcuda.so`). So I linked the libcuda.so from `/lib/x86_64-linux-gnu` to this folder with the following command: 

```
ls -s /usr/lib/x86_64-linux-gnu/libcuda.so miniconda3/envs/<env_path>/lib/libcuda.so
```

I don't know if that is the right libcuda.so to be linked, but installation completed and I was able to import the tinycudann module.

**Comment by akshay-krishnan** [comment]
So I tried replicating this in a new environment, and the fix does not work for me anymore. Its not able to find lcuda even though I have a symlink to libcuda.so in the lib folder that it is searching in. 

@Tom94 any help here would be great!

**Comment by akshay-krishnan** [comment]
I also tried with cuda 11.7, but I face the same problem, so this is probably not version-specific.

**Comment by olestole** [comment]
I was able to resolve my issue regarding `-lcuda` which couldn't be found by following @akshay-krishnan's symlink-solution

**Comment by yenchenlin** [comment]
Add the following line to your `.bashrc` / `.zshrc` should solve the problem:

```
export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
```

**Comment by ry85** [comment]
The answer from @akshay-krishnan worked for me also,

ln -s /usr/lib/x86_64-linux-gnu/libcuda.so anaconda3/envs/nerfstudio/lib/libcuda.so

and not,

export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"

It seems there is no clear-cut solution to this problem, right now.

**Comment by KamiCalcium** [comment]
> Add the following line to your `.bashrc` or `.zshrc` (depending on your shell) should solve the problem:
> 
> ```
> export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
> ```
I'm able to install
```
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```
After setting the path to /usr/local/cuda/lib64/stubs, thank you!

However, when I tried to run instant-NGP under nerfstudio I have this error:
```
FAILED: nerfacc_cuda.so 
c++ pybind.cuda.o render_weight.cuda.o pack.cuda.o cdf.cuda.o render_transmittance.cuda.o intersection.cuda.o render_transmittance_cub.cuda.o contraction.cuda.o ray_marching.cuda.o -shared -L/home/user/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/home/user/anaconda3/envs/nerfstudio/lib64 -lcudart -o nerfacc_cuda.so
/usr/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
I tried 
```
export LIBRARY_PATH="/usr/local/cuda/lib64:$LIBRARY_PATH"
```
since I do found libcudart.so under /usr/local/cuda/lib64 but it does not resolve the issue. Any suggestions? Thank you very much!

**Comment by Tom94** [comment]
@KamiCalcium I'm afraid that's an issue on [NerfAcc](https://www.nerfacc.com/en/latest/)'s side, not tcnn.

**Comment by MilkClouds** [comment]
I've solved lcuda not found issue, on WSL2

by executing `ln -s /usr/lib/wsl/lib/libcuda.so ~/anaconda3/envs/nsml/lib/libcuda.so`

**Comment by MilkClouds** [comment]
I've solved lcuda not found issue, on WSL2

by executing `ln -s /usr/lib/wsl/lib/libcuda.so ~/anaconda3/envs/(your env)/lib/libcuda.so`

may be helpful to someone.

**Comment by xiechun0318** [comment]
I had the same problem installing it in a conda env on WSL. Here is how I solved it.

the compiler tries to find `libcuda.so` in `~/miniconda3/envs/(envname)/lib`, but for some reason CUDA installed it to` /home/(userneme)/miniconda3/envs/(envname)/lib/sutbs`

so I just created a link for `libcuda.so` outside the` /stub` folder by` ln -s  ~/miniconda3/envs/(envname/lib/stubs/libcuda.so ~/miniconda3/envs/xrnerf/lib/libcuda.so`

Then it compiled with no error.

I hope it helps.

**Comment by Eric-Ho-Matrix** [comment]
> Add the following line to your `.bashrc` or `.zshrc` (depending on your shell) should solve the problem:
> 
> ```
> export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
> ```

Just to record, this method also works for WSL2 (Ubuntu 20.02 LTS)

**Comment by whoiszzj** [comment]
I meet the same problem and solve it with 
`ln -s /usr/lib/x86_64-linux-gnu/libcuda.so miniconda3/envs/<env_path>/lib/libcuda.so`
**Note that the libcuda.so must from the Nvidia Driver Lib, not Cuda Lib**
Nvidia Driver Lib:
![image](https://github.com/NVlabs/tiny-cuda-nn/assets/38402402/9a99f7dc-12ad-4530-af79-16bc90cfcda1)
Cuda lib: <cuda_home>/lib64/stubs:
![image](https://github.com/NVlabs/tiny-cuda-nn/assets/38402402/691829f6-ee35-4651-9bce-74a065d345a6)

Good luck!

**Comment by lenismerino** [comment]
> I've solved lcuda not found issue, on WSL2
> 
> by executing `ln -s /usr/lib/wsl/lib/libcuda.so ~/anaconda3/envs/(your env)/lib/libcuda.so`
> 
> may be helpful to someone.

It also worked on WSL2 Ubuntu 22.04.02, CUDA 11.8 with cudnn8, Python 3.10 via pip

**Comment by lenismerino** [comment]
> > Add the following line to your `.bashrc` or `.zshrc` (depending on your shell) should solve the problem:
> > ```
> > export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
> > ```
> 
> Just to record, this method also works for WSL2 (Ubuntu 20.02 LTS)

This also worked on WSL2 Ubuntu 22.04.02,  cuda 11.8 with cudnn, Python 3.10 via pip

**Comment by Zazexy** [comment]
> Add the following line to your `.bashrc` or `.zshrc` (depending on your shell) should solve the problem:
> 
> ```
> export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
> ```

It works perfectly! thx!

**Comment by samsartor** [comment]
The `LIBRARY_PATH` solution did not work for me, but `export LDFLAGS=-L/usr/local/cuda/lib64/stub` did.

**Comment by qgli** [comment]
I tried with @Zazexy and @samsartor's method:

```bash
export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
export LDFLAGS=-L/usr/local/cuda/lib64/stub

and it works for me, thank you!
specs: RTX4070ti, windows11, cuda11.8, gcc 11 and pytorch 2.0.1

**Comment by kwand** [comment]
I can confirm the above solution works, though there seems to be a typo (second line should be `export LDFLAGS=-L/usr/local/cuda/lib64/stubs`, with an 's' for `stubs`).

On CUDA 11.8, PyTorch 2.0, GCC11 (all within an conda env).

Many thanks, and I hope this is fixed soon.

**Comment by jeff999955** [comment]
> The `LIBRARY_PATH` solution did not work for me, but `export LDFLAGS=-L/usr/local/cuda/lib64/stub` did.

This works for me, thanks!

**Comment by wy-luke** [comment]
> I had the same problem installing it in a conda env on WSL. Here is how I solved it.
> 
> the compiler tries to find `libcuda.so` in `~/miniconda3/envs/(envname)/lib`, but for some reason CUDA installed it to` ~/miniconda3/envs/(envname)/lib/stubs`
> 
> so I just created a link for `libcuda.so` outside the` /stubs` folder by` ln -s ~/miniconda3/envs/(envname/lib/stubs/libcuda.so ~/miniconda3/envs/xrnerf/lib/libcuda.so`
> 
> Then it compiled with no error.
> 
> I hope it helps.

Great! It's the problem.

You could also run `export LIBRARY_PATH=".../conda/envs/env_name/lib/stubs/:$LIBRARY_PATH"`.

> Replace the path to yours

It works for me. Thanks.

**Comment by gary-young** [comment]
> > The `LIBRARY_PATH` solution did not work for me, but `export LDFLAGS=-L/usr/local/cuda/lib64/stub` did.
> 
> This works for me, thanks!

LDFLAGS works for me!! Thanks!!

**Comment by pengc02** [comment]
> Sorry for the late response folks.
> 
> There was a libcuda.so in this path on my system `/lib/x86_64-linux-gnu/libcuda.so`, but I think that path is not included in LD's library path. I saw that the linked library path in my command is the /lib folder in my conda environment (`miniconda3/envs/<env_name>/lib/libcuda.so`). So I linked the libcuda.so from `/lib/x86_64-linux-gnu` to this folder with the following command:
> 
> ```
> ln -s /usr/lib/x86_64-linux-gnu/libcuda.so miniconda3/envs/<env_path>/lib/libcuda.so
> ```
> 
> I don't know if that is the right libcuda.so to be linked, but installation completed and I was able to import the tinycudann module.

this works, and if there's no libcuda.so in /usr/lib/x86_64-linux-gnu/, you can symlink one using libcuda.so.1 or something like that by 
```
ln -s libcuda.so.1 libcuda.so
```

**Comment by Invisiphantom** [comment]
`export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/wsl/lib`
This works for me.

**Comment by CXavireH** [comment]
首先可以尝试`strace -o trace.log python setup.py install`来输出详细信息，然后查看 trace.log 文件内容，搜索 libcuda.so 相关的条目，看看在哪一步出了问题。
根据我的输出，我的解决方法是修改 setup.py： 在 setup.py 文件中，你可以尝试修改链接器的选项，显式地指定 libcuda.so.1 的路径。具体可以在 setup.py 中设置 extra_link_args 或通过其他方式添加 -L/usr/lib/x86_64-linux-gnu/ 和 -lcuda。
我在`setup.py`里面的`mask_extension()`里面加上了
```
library_dirs=[
'/usr/local/cuda-11.8/lib64',
'/usr/lib/x86_64-linux-gnu'
],
```

**Comment by geeteshCh** [comment]
For those who have cuda installed locally in the conda environment, https://github.com/NVlabs/tiny-cuda-nn/issues/183#issuecomment-1405541078 this solution should work.

**Comment by ramintoosi** [comment]
My problem was with

```python
torch._inductor.aoti_compile_and_package

```

I installed everything (including cudatoolkit) with conda, and I used this to solve the problem

```bash
ln -s $CONDA_PREFIX/lib/stubs/libcuda.so \
      $CONDA_PREFIX/lib/libcuda.so
ln -s $CONDA_PREFIX/lib/stubs/libcuda.so \
      $CONDA_PREFIX/lib/libcuda.so.1
```
