### ISSUE TITLE
multi_stream illegal memory access

### ISSUE THREAD

**Issue by tancik** [NVlabs/tiny-cuda-nn#272]
Running with latest gives the following error.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /tmp/pip-req-build-c1sq9878/include/tiny-cuda-nn/multi_stream.h:83 cudaEventRecord(m_event, m_stream) failed with error an illegal memory access was encountered
Aborted (core dumped)
```
This has been noted by multiple nerfstudio users.

Reverting to e4c147e36893bef3a065b1e5db69706951ea4d56 resolves the issue.

**Comment by Tom94** [comment]
Could you try 5e61f55a2f0c0339bb0939ca9aadefd54bdbd2a5 and let me know whether it fixes the issue?

**Comment by tancik** [comment]
That did the trick!

**Comment by Tom94** [comment]
This seems to indicate that PyTorch doesn't guarantee memory alignment of its parameter tensors, which is unfortunate for performance... I would have expected at least multiples of a cache line, which seemed to hold on my system. Oh well, rolling back the optimization on `master`. :(

Thanks for checking in any case, and sorry for the inconvenience.

**Comment by tancik** [comment]
Thanks for the speedy fix!
